Increase timeouts for SegmentRunner in SegmentRunnerTest.
Test failures were like:
```
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.531 sec <<< FAILURE! - in io.cassandrareaper.unit.service.SegmentRunnerTest
failureTest(io.cassandrareaper.unit.service.SegmentRunnerTest)  Time elapsed: 1.053 sec  <<< ERROR!
java.util.concurrent.ExecutionException: java.lang.AssertionError: expected:<RUNNING> but was:<NOT_STARTED>
  at io.cassandrareaper.unit.service.SegmentRunnerTest.failureTest(SegmentRunnerTest.java:366)
Caused by: java.lang.AssertionError: expected:<RUNNING> but was:<NOT_STARTED>
```